# -*- coding: utf-8 -*-
"""selfassessment3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o5L6aTOD2kNWWGx3BkmDORdYQQTy1J-P
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

train = pd.read_csv("train_LZdllcl.csv")
test = pd.read_csv("test_2umaH9m.csv")
sample = pd.read_csv("sample_submission_M0L0uXE.csv")

train.head()

train.shape

train.info()

train.describe()

train.isnull().sum()

train.duplicated().sum()

train["education"].value_counts()

train["previous_year_rating"].value_counts()

import matplotlib.pyplot as plt
import seaborn as sns

num_cols = train.select_dtypes(include=['int64', 'float64']).columns

plt.figure(figsize=(20, 14))

for i, col in enumerate(num_cols):
    plt.subplot(4, 4, i + 1)
    sns.histplot(train[col], kde=True)
    plt.title(col)

plt.tight_layout()
plt.show()

train["education"] = train["education"].fillna(train["education"].mode()[0])

train["previous_year_rating"] = train["previous_year_rating"].fillna(train["previous_year_rating"].median())

train.isnull().sum()

num_col = train.select_dtypes(include=["int64", "float64"]).columns

for col in num_col:
    sns.boxplot(y=train[col])
    plt.title(col)
    plt.show()

Q1 = train["previous_year_rating"].quantile(0.25)
Q3 = train["previous_year_rating"].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

train["previous_year_rating"] = train["previous_year_rating"].clip(lower, upper)

from scipy.stats.mstats import winsorize

train["age"] = winsorize(train["age"], limits=[0.02, 0.02])

train["length_of_service"] = winsorize(train["length_of_service"], limits=[0.03, 0.03])

train["avg_training_score"] = winsorize(train["avg_training_score"], limits=[0.01, 0.01])

Q1 = train["no_of_trainings"].quantile(0.25)
Q3 = train["no_of_trainings"].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

train["no_of_trainings"] = train["no_of_trainings"].clip(lower, upper)

num_col = train.select_dtypes(include=["int64", "float64"]).columns

for col in num_col:
    sns.boxplot(y=train[col])
    plt.title(col)
    plt.show()

cat_col = train.select_dtypes(include="object").columns
cat_col

for col in cat_col:
    print(col)
    print(train[col].unique())
    print("-------------------")

train = pd.get_dummies(
    train,
    columns=["department", "region", "recruitment_channel"],
    prefix=["de", "re", "recru"],
    drop_first=True,
    dtype=int
)

train["gender"] = train["gender"].map({
    "m": 1,
    "f": 0
})

from sklearn.preprocessing import OrdinalEncoder

oe = OrdinalEncoder(categories=[[
    "Below Secondary",
    "Bachelor's",
    "Master's & above"
]])

train[["education"]] = oe.fit_transform(train[["education"]])

train.head()

train.columns

X = train.drop(["employee_id", "is_promoted"], axis=1)
y = train["is_promoted"]

from sklearn.model_selection import train_test_split

X_train, X_valid, y_train, y_valid = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("X_train:", X_train.shape)

print("y_train:", y_train.shape)

train["is_promoted"].value_counts()

from sklearn.linear_model import LogisticRegression

lr = LogisticRegression(
    random_state=42,
    class_weight="balanced",
    max_iter=1000
)

lr.fit(X_train, y_train)

y_pred = lr.predict(X_valid)

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

print("Accuracy:", accuracy_score(y_valid, y_pred))
print(confusion_matrix(y_valid, y_pred))
print(classification_report(y_valid, y_pred))

from sklearn.tree import DecisionTreeClassifier

dt = DecisionTreeClassifier(random_state=42)

dt.fit(X_train, y_train)

y_pred_dt = dt.predict(X_valid)

print("Accuracy:", accuracy_score(y_valid, y_pred_dt))
print(confusion_matrix(y_valid, y_pred_dt))
print(classification_report(y_valid, y_pred_dt))

from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(
    random_state=42,
    class_weight="balanced"
)

rf.fit(X_train, y_train)

y_pred_rf = rf.predict(X_valid)

print("Accuracy:", accuracy_score(y_valid, y_pred_rf))
print(confusion_matrix(y_valid, y_pred_rf))
print(classification_report(y_valid, y_pred_rf))

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
import pandas as pd

results = pd.DataFrame({
    "Model": ["Logistic Regression", "Decision Tree", "Random Forest"],
    "Accuracy": [
        accuracy_score(y_valid, y_pred),
        accuracy_score(y_valid, y_pred_dt),
        accuracy_score(y_valid, y_pred_rf)
    ],
    "Precision": [
        precision_score(y_valid, y_pred),
        precision_score(y_valid, y_pred_dt),
        precision_score(y_valid, y_pred_rf)
    ],
    "Recall": [
        recall_score(y_valid, y_pred),
        recall_score(y_valid, y_pred_dt),
        recall_score(y_valid, y_pred_rf)
    ],
    "F1-Score": [
        f1_score(y_valid, y_pred),
        f1_score(y_valid, y_pred_dt),
        f1_score(y_valid, y_pred_rf)
    ]
})

results

from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(
    n_estimators=300,
    max_depth=15,
    min_samples_split=5,
    min_samples_leaf=2,
    class_weight="balanced",
    random_state=42
)

rf.fit(X_train, y_train)

y_pred_rf = rf.predict(X_valid)

print("Accuracy:", accuracy_score(y_valid, y_pred_rf))
print(confusion_matrix(y_valid, y_pred_rf))
print(classification_report(y_valid, y_pred_rf))

"""# Random Forest with class_weight='balanced'
# Result: Recall improved but Accuracy and F1 decreased
"""

from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(random_state=42)

param_grid = {
    "n_estimators": [100, 200],
    "max_depth": [10, 20, None],
    "min_samples_split": [2, 5],
    "min_samples_leaf": [1, 2]
}

grid = GridSearchCV(
    estimator=rf,
    param_grid=param_grid,
    cv=5,
    scoring="f1",
    n_jobs=-1
)

grid.fit(X_train, y_train)

print("Best Parameters:", grid.best_params_)
print("Best CV F1 Score:", grid.best_score_)

best_rf = grid.best_estimator_

y_pred_tuned = best_rf.predict(X_valid)

from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

print("Accuracy:", accuracy_score(y_valid, y_pred_tuned))
print(confusion_matrix(y_valid, y_pred_tuned))
print(classification_report(y_valid, y_pred_tuned))

!pip install xgboost

from xgboost import XGBClassifier

xgb = XGBClassifier(
    random_state=42,
    eval_metric="logloss"
)

xgb.fit(X_train, y_train)

y_pred_xgb = xgb.predict(X_valid)

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

print("Accuracy:", accuracy_score(y_valid, y_pred_xgb))
print(confusion_matrix(y_valid, y_pred_xgb))
print(classification_report(y_valid, y_pred_xgb))

from xgboost import XGBClassifier

xgb_final = XGBClassifier(
    random_state=42,
    eval_metric="logloss"
)

xgb_final.fit(X, y)

test = pd.read_csv("/content/test_2umaH9m.csv")
test.head()

test_ids = test["employee_id"]

test.drop("employee_id", axis=1, inplace=True)

test.shape

test.isnull().sum()

test.duplicated().sum()

test.info()

test["education"] = test["education"].fillna(train["education"].mode()[0])

test["previous_year_rating"] = test["previous_year_rating"].fillna(train["previous_year_rating"].median())

test.isnull().sum()

test.head()

test = pd.get_dummies(
    test,
    columns=["department", "region", "recruitment_channel"],
    prefix=["de", "re", "recru"],
    drop_first=True,
    dtype=int
)

test["gender"] = test["gender"].map({
    "m": 1,
    "f": 0
})

test["education"].unique()

test["education"] = test["education"].replace(1.0, "Bachelor's")

test[["education"]] = oe.transform(test[["education"]])

test.head()

test = test.reindex(columns=X.columns, fill_value=0)

print(X.shape)
print(test.shape)

print(X.columns.equals(test.columns))

pred = xgb_final.predict(test)

submission = pd.read_csv("/content/sample_submission_M0L0uXE.csv")

submission.head()

submission["is_promoted"] = pred

submission.to_csv("submission.csv", index=False)

submission.head()

import numpy as np

np.unique(pred, return_counts=True)

submission["is_promoted"].value_counts()

from sklearn.model_selection import StratifiedKFold, RandomizedSearchCV
from xgboost import XGBClassifier

from sklearn.model_selection import StratifiedKFold

skf = StratifiedKFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)

from xgboost import XGBClassifier

xgb = XGBClassifier(
    random_state=42,
    eval_metric="logloss"
)

param_dist = {
    "n_estimators": [100, 200, 300, 400, 500, 700],
    "max_depth": [3, 4, 5, 6, 7, 8],
    "learning_rate": [0.01, 0.03, 0.05, 0.1],
    "subsample": [0.7, 0.8, 0.9, 1.0],
    "colsample_bytree": [0.7, 0.8, 0.9, 1.0],
    "min_child_weight": [1, 3, 5],
    "gamma": [0, 0.1, 0.2, 0.3]
}

from sklearn.model_selection import RandomizedSearchCV

random_search = RandomizedSearchCV(
    estimator=xgb,
    param_distributions=param_dist,
    n_iter=30,
    scoring="f1",
    cv=skf,
    random_state=42,
    n_jobs=-1,
    verbose=2
)

random_search.fit(X_train, y_train)

print(random_search.best_params_)
print(random_search.best_score_)

best_xgb = random_search.best_estimator_

y_pred = best_xgb.predict(X_valid)

from sklearn.metrics import accuracy_score, classification_report

print("Accuracy:", accuracy_score(y_valid, y_pred))
print(classification_report(y_valid, y_pred))

best_xgb.fit(X, y)

pred = best_xgb.predict(test)

submission["is_promoted"] = pred

submission.to_csv("submission_tuned_v2.csv", index=False)

